<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AudioSeparator.Abstractions\AudioSeparator.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.0-beta</Version>
    <PackageVersion>0.1.0-beta</PackageVersion>
    <Description>FFMPEG reader and write extensions for the AudioSeparator library.</Description>
  </PropertyGroup>

</Project>
