<Project>
  <PropertyGroup>
    <Authors>Gabriel Oliveira Brito</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/gabrieloliveirabrito/AudioSeparator</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Copyright>Copyright (c) Gabriel Oliveira Brito</Copyright>
  </PropertyGroup>

  <PropertyGroup Condition="Exists('$(MSBuildProjectDirectory)/README.md')">
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup Condition="Exists('$(MSBuildProjectDirectory)/README.md')">
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
